name: XcraftChat
main: de.xcraft.engelier.chat.Chat
version: 0.5
author: Engelier
load: postworld
commands:
  xchat:
    description: Reloads the config
    usage: /<command>
  a:
    description: Use the admin chat
    usage: /<command> <message>
  c:
    description: Use the admin chat
    usage: /<command> <message>
#    permission: XcraftChat.reload
permissions:
  XcraftChat.reload:
    default: OP
    description: allows you to reload the config
  XcraftChat.admin:
    default: OP
    description: allows using the adminchat
  XcraftChat.team:
    default: OP
    description: allows using the teamchat
